# Generated by Django 5.2.11 on 2026-03-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_load_data,py'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Herald', 'Хранитель'), ('Guardian', 'Страж'), ('Crusader', 'Рыцарь'), ('Archon', 'Архонт'), ('Legend', 'Легенда'), ('Ancient', 'Древний'), ('Divine', 'Божество'), ('Immortal', 'Титан')], default='Herald', max_length=20, verbose_name='Ранг'),
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='Биография')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Информация о преподавателе',
                'verbose_name_plural': 'Информация о преподавателях',
            },
        ),
    ]
