# Generated by Django 5.2.11 on 2026-03-24 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_teacher_options_remove_teacher_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-rating', '-experience_years'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Длительность (часов)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимум студентов'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной')], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Удовлетворительно'), ('2', 'Неудовлетворительно')], max_length=2, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='student',
            name='dota_mmr',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15000)], verbose_name='MMR'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='student',
            name='steam_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Steam ID должен содержать 17 цифр', regex='^[0-9]{17}$')], verbose_name='Steam ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50, message='Опыт не может превышать 50 лет')], verbose_name='Лет опыта'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX или 8XXXXXXXXXX', regex='^\\+?7\\d{10}$|^8\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (0-5)'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Telegram должен начинаться с @ и содержать 5-32 символов', regex='^@[a-zA-Z0-9_]{5,32}$')], verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Записан'), ('COMPLETED', 'Завершил'), ('DROPPED', 'Отчислен')], default='ENROLLED', max_length=10, null=True),
        ),
    ]
