# Generated by Django 5.2.11 on 2026-03-31 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_course_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='is_verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX или 8XXXXXXXXXX', regex='^\\+?7\\d{10}$|^8\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Рейтинг'),
        ),
    ]
